In [ ]:

import numpy as np
# traverses vertices reachable from s.
from collections import defaultdict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
offset_list = np.zeros(30)
with open('/content/drive/MyDrive/Colab Notebooks/HW2/HW_2.2.txt') as f:
    lines = f.readlines()
print(len(lines))

offset_list = np.zeros((len(lines),3))
for i in range(len(lines)):
  offset_list[i] = lines[i].split(",")
print(offset_list)

30
[[ 7.       9.      -4.851  ]
 [ 7.       2.       2.9585 ]
 [ 7.       5.      -4.3057 ]
 [ 7.       3.       1.9569 ]
 [ 7.       4.       4.4298 ]
 [ 7.       0.      -0.57024]
 [ 9.       0.       4.9738 ]
 [ 9.       3.       6.7302 ]
 [ 9.       4.       9.3592 ]
 [ 9.       2.       8.1628 ]
 [ 9.       6.       1.361  ]
 [ 0.       4.       4.8603 ]
 [ 0.       5.      -3.9274 ]
 [ 0.       8.       3.426  ]
 [ 0.       6.      -3.5175 ]
 [ 0.       1.       0.83131]
 [ 4.       8.      -1.3038 ]
 [ 4.       1.      -3.9057 ]
 [ 4.       5.      -9.2724 ]
 [ 4.       2.      -1.9237 ]
 [ 8.       6.      -6.5603 ]
 [ 8.       2.      -0.56773]
 [ 8.       1.      -2.9797 ]
 [ 8.       5.      -8.4274 ]
 [ 8.       3.      -2.1633 ]
 [ 6.       2.       6.5333 ]
 [ 2.       5.      -7.8453 ]
 [ 2.       1.      -2.3873 ]
 [ 3.       1.      -1.1802 ]
 [ 5.       1.       4.9125 ]]


In [ ]:
arr = np.zeros((10,10))
for i in offset_list:
  arr[int(i[0])][int(i[1])] = i[2]

print(arr)

[[ 0.       0.83131  0.       0.       4.8603  -3.9274  -3.5175   0.
   3.426    0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.
   0.       0.     ]
 [ 0.      -2.3873   0.       0.       0.      -7.8453   0.       0.
   0.       0.     ]
 [ 0.      -1.1802   0.       0.       0.       0.       0.       0.
   0.       0.     ]
 [ 0.      -3.9057  -1.9237   0.       0.      -9.2724   0.       0.
  -1.3038   0.     ]
 [ 0.       4.9125   0.       0.       0.       0.       0.       0.
   0.       0.     ]
 [ 0.       0.       6.5333   0.       0.       0.       0.       0.
   0.       0.     ]
 [-0.57024  0.       2.9585   1.9569   4.4298  -4.3057   0.       0.
   0.      -4.851  ]
 [ 0.      -2.9797  -0.56773 -2.1633   0.      -8.4274  -6.5603   0.
   0.       0.     ]
 [ 4.9738   0.       8.1628   6.7302   9.3592   0.       1.361    0.
   0.       0.     ]]


In [ ]:
class Graph:

  def __init__(self, vertices):
    self.V = vertices
    self. graph = defaultdict(list)
    self.offset = 0 
    self.count = 1
    self.off = 0
  
  def addEdge(self, u, v):
    self. graph[u].append(v)

  def AllPathsUtil(self, u,d, visited, path, array):
    
    visited[u] = True
    path.append(u)

    if u==d:
      #print(path)
      self.count = self.count +1
      off=0
      for i in range(len(path)-1):
        off = off + array[path[i]][path[i+1]]
      self.offset = (self.offset + off)
      #print(off)
      #print(self.offset)
      #print(self.count)
    else:
      for i in self.graph[u]:
        if visited[i] ==False:
          self.AllPathsUtil(i, d, visited, path,array)

    path.pop()
    visited[u] = False


  def AllPaths(self, s,d, array):
    visited = [False]*(self.V)
    path = []
    self.count = 1
    self.offset = 0
    self.AllPathsUtil(s, d, visited, path, array)
    self.offset = self.offset/(self.count-1)
   

g = Graph(10)
for i in offset_list:
  g.addEdge(int(i[0]), int(i[1]))

s = 0; 
for i in [8 , 6, 5, 4, 3, 2, 1]:
  g.AllPaths(s,i, arr)
  print('offset of ', i, ': ',g.offset)

g.AllPaths(7,0, arr)
print('offset of ', 7, ': ',g.offset)
g.AllPaths(9,0, arr)
print('offset of ', 9, ': ',g.offset)

# This code is contributed by Neelam Yadav

offset of  8 :  3.49125
offset of  6 :  -3.2185333333333332
offset of  5 :  -4.655565999999999
offset of  4 :  4.8603
offset of  3 :  1.32795
offset of  2 :  3.1213233333333332
offset of  1 :  0.4580904545454541
offset of  7 :  -0.22372000000000009
offset of  9 :  4.9738
